---
title: "Tidy Analysis of OSYM Data"
author: Gülnur Acar
date: April 30, 2018
output:
  html_document:
    toc: false
  pdf_document:
    toc: false
    toc_depth: 3
---


library(tidyverse)


osym_data_2017 <- 
  osym_data_2017 %>% mutate(general_quota = as.numeric(general_quota), general_placement = as.numeric(general_placement)) 
head(osym_data_2017)


First of all, osym data is printed for understanding format of data.

print(osym_data_2017) 



1. Get the highest `max_score` programs from each `exam_type`.
 
 
osym_data_2017%>%
    group_by(exam_type)%>%
      arrange(desc(max_score))%>%
        slice(1)



2. Get and plot the top 10 programs of BOÐAZÝÇÝ ÜNÝVERSÝTESÝ in terms of total max_score in a bar chart.


filtered_boðaziçi <- osym_data_2017 %>% filter(university_name=="BOÐAZÝÇÝ ÜNÝVERSÝTESÝ")

filtered_boðaziçi %>% arrange(desc(max_score))
    
osym_data_2017%>%
  filter(university_name=='BOÐAZÝÇÝ ÜNÝVERSÝTESÝ')%>%
    arrange(desc(max_score))%>%
      slice(1:10)%>%
        ggplot()+geom_bar(aes(x=reorder(program_name,-max_score),y=max_score),stat="Identity") + theme(axis.text.x=element_text(angle=90)) 
        
     
      
3. Get comparation the computer engineering (Bilgisayar Mühendisliði) and mechanical engineering (Makine Mühendisliði) programs. Make the university rank according to the maximum score of them. Calculate the average maximum score and look at the fillrates.


Com <- osym_data_2017 %>% filter(grepl("Bilgisayar Mühendisliði", program_name))

Mech <- osym_data_2017 %>% filter(grepl("Makine Mühendisliði", program_name))

Com %>% mutate(avg_score= (max_score + min_score)/2, Fill_rate= general_placement/general_quota) %>% arrange(desc(avg_score)) %>% slice(1:10)

Mech %>% mutate(avg_score= (max_score + min_score)/2, Fill_rate= general_placement/general_quota) %>% arrange(desc(avg_score)) %>% slice(1:10)

com2 <-osym_data_2017 %>% select (university_name, program_name, max_score, general_placement, general_quota ) %>% filter(program_name == "Bilgisayar Mühendisliði" ) %>% summarise(mean_com2 = mean(max_score) , fillrate = sum(general_placement)/sum(general_quota))
com2

mech2 <-osym_data_2017 %>% select (university_name, program_name, max_score, general_placement, general_quota ) %>% filter(program_name == "Makine Mühendisliði" ) %>% summarise(mean_mech2 = mean(max_score) , fillrate = sum(general_placement)/sum(general_quota))
mech2


Max score for computer engineering departments is higher than mechanical engineering departmens in average, moreover fill rate to the computer engineering departments is higher than to the mechanical engineering programs.
